#!/usr/bin/perl

use strict;

# Import the library path TEXTPRESSO_LIB from TextpressoLibrary.pm
use TextpressoLibrary;

use lib TEXTPRESSO_LIB;

use CGI;
use TextpressoDatabaseGlobals;

### globals
#

# handle to this CGI and own address
my $query = new CGI;
my $absmyself = $query->url(absolute=>1);

### process form
#

#
###

PrintHeader($query);

### first part of output goes here
#

my $file_name = $query->param('filename');
my $file_name = DB_TMP . '/' . $file_name;
open (IN, "<$file_name") || die ("Could not open $file_name for reading.");

my $sen = "";
while (<IN>)
{	$sen .= $_;
}
close (IN);
print $query->start_b;
print $query->font("Sentence: ");
print $query->end_b;
print $query->start_a;
print "$sen";
print $query->end_a;
#
###

### end form here
#

PrintBottom($query);

#
###

sub PrintHeader { # begin PrintHeader
    
    my $query = shift;
    
    print $query->header;
    print $query->start_html(-title=>'Show Sentence', -author=>'adapted by Arun Rangarajan from Hans-Michael Muller');
    
} # end PrintHeader

sub PrintBottom { # begin PrintBottom

    my $query = shift;

    print $query->end_html;

}   # end PrintBottom
